# Generated by Django 4.2.7 on 2023-11-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=200)),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_cantidad', models.IntegerField()),
                ('profundidad', models.FloatField(blank=True, default=70, null=True)),
                ('alto', models.FloatField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('tipo_de_terminacion', models.CharField(blank=True, max_length=500, null=True)),
                ('precio_producto', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, null=True)),
                ('descripcion', models.TextField(max_length=1000)),
                ('profundidad', models.FloatField(blank=True, default=70, null=True)),
                ('alto', models.FloatField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('tipo_de_terminacion', models.CharField(blank=True, max_length=500, null=True)),
                ('precio_producto', models.IntegerField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('accesorios', models.ManyToManyField(blank=True, null=True, to='presupuesto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoProductoAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesorio_cantidad', models.IntegerField()),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.producto')),
                ('presupuesto_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.presupuestoproducto')),
            ],
        ),
        migrations.AddField(
            model_name='presupuestoproducto',
            name='id_accesorio',
            field=models.ManyToManyField(related_name='presupuesto_accesorios', through='presupuesto.PresupuestoProductoAccesorio', to='presupuesto.producto'),
        ),
        migrations.AddField(
            model_name='presupuestoproducto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.presupuesto'),
        ),
        migrations.AddField(
            model_name='presupuestoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_productos', to='presupuesto.producto'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='id_producto',
            field=models.ManyToManyField(through='presupuesto.PresupuestoProducto', to='presupuesto.producto'),
        ),
    ]
