# Generated by Django 4.2.7 on 2023-11-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestoproductoaccesorio',
            name='accesorio_cantidad',
        ),
    ]
