# Generated by Django 4.2.7 on 2023-11-20 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_remove_presupuestoproductoaccesorio_accesorio_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, null=True)),
                ('descripcion', models.TextField(max_length=1000)),
                ('precio_accesorio', models.IntegerField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='presupuestoproducto',
            name='id_accesorio',
            field=models.ManyToManyField(related_name='presupuesto_accesorios', through='presupuesto.PresupuestoProductoAccesorio', to='presupuesto.accesorio'),
        ),
        migrations.AlterField(
            model_name='presupuestoproductoaccesorio',
            name='accesorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.accesorio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='accesorios',
            field=models.ManyToManyField(blank=True, null=True, to='presupuesto.accesorio'),
        ),
    ]
