# Generated by Django 4.2.5 on 2023-11-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_accesorio_alter_presupuestoproducto_id_accesorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoproducto',
            name='id_accesorio',
            field=models.ManyToManyField(blank=True, related_name='presupuesto_accesorios', through='presupuesto.PresupuestoProductoAccesorio', to='presupuesto.accesorio'),
        ),
        migrations.AlterField(
            model_name='presupuestoproducto',
            name='profundidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
